services:
  urinereportcheck:
    build:
      context: ./urine-report-check
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=prod
    ports:
      - "5001:5001"
    restart: unless-stopped

  bloodreportcheck:
    build:
      context: ./blood-report-check
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=prod
    ports:
      - "5002:5002"
    restart: unless-stopped
