# ingress for routinh : 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blood-api-ingress
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/analyze
        pathType: Prefix
        backend:
          service:
            name: bloodsvc
            port:
              number: 5002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blood-ui-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /blood-report-check(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: bloodsvc
            port:
              number: 5002
      - path: /urine-report-check(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: urinesvc
            port:
              number: 5001
