apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /patient-register(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: patsvc1
            port:
              number: 5003
      - path: /css/(.*)
        pathType: Prefix
        backend:
          service:
            name: patsvc1
            port:
              number: 5003
      - path: /js/(.*)
        pathType: Prefix
        backend:
          service:
            name: patsvc1
            port:
              number: 5003
      - path: /blood-report-check
        pathType: Prefix
        backend:
          service:
            name: bloodsvc
            port:
              number: 5002
      - path: /urine-report-check
        pathType: Prefix
        backend:
          service:
            name: urinesvc
            port:
              number: 5001
