apiVersion: v1
kind: ServiceAccount 
metadata: 
  name: jenkins-sa
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata: 
  name: jenkins-role
rules: 
- apiGroups: ["", "apps", "rbac.authorization.k8s.io", "scheduling.k8s.io", "autoscaling"]
  resources: ["deployments", "replicasets", "configmaps", "services", "persistentvolumeclaims", "persistentvolumes", "priorityclasses", "horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-role-binding
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: prod
roleRef:
  kind: ClusterRole
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
