apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-reg-config
  namespace: prod
data:
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "465"
  MAIL_USE_TLS: "false"
  MAIL_USE_SSL: "true"
  ADMIN_EMAIL: "mehdifurkhan00@gmail.com"
  SQLALCHEMY_DATABASE_URI: "sqlite:////app/data/site.db"
---
apiVersion: v1
kind: Secret
metadata:
  name: patient-reg-secret
  namespace: prod
data:
  SECRET_KEY: "NWRlMjNmMTMxNzU1Njg3MzQyMjMxYmQzMzdlMTBhODMwYzRkYTIwYmNiMTVhOTBkNjNmODk4MmFjNmZhNzRmYw=="
  MAIL_USERNAME: "bWVoZGlmdXJraGFuMDAzQGdtYWlsLmNvbQ=="
  MAIL_PASSWORD: "b3JwZiBvcWVxIGZ4emggYWt3cw=="
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: patregpc
value: 100000
globalDefault: false
description: "Priority class for Patient Registration"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-reg
  namespace: prod
  labels:
    app: patient
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      tier: patreg
  template:
    metadata:
      labels:
        tier: patreg
    spec:
      priorityClassName: patregpc
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: patregcon
          image: furkhan2000/shark:patient-reg
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: patient-reg-config
            - secretRef:
                name: patient-reg-secret
          resources:
            requests:
              cpu: "250m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 8
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: patientnp
  namespace: prod
spec:
  podSelector:
    matchLabels:
      tier: patreg
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - ports:
        - protocol: TCP
          port: 5002
        - protocol: TCP
          port: 5001
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 465
---
apiVersion: v1
kind: Service
metadata:
  name: patsvc1
  namespace: prod
spec:
  type: NodePort
  selector:
    tier: patreg
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
      nodePort: 5003
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpapatient
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: patient-reg
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
